Sorry: IndentationError: expected an indented block after 'except' statement on line 27 (checkpoints_random.py, line 29)
